server:
  port: 80

  
 ### **********************************其他配置*****************************************
study: 
  name: chenjunle
  age: 19
  
  ### **********************************其他配置*****************************************
spring: 
  profiles:
    active:
      - dev
      
debug: true